When modifying existing columns in views, Postgres restricts name and type changes to existing columns as describes in the documentation:

 

"if a view of the same name already exists, it is replaced. The new query must generate the same columns that were generated by the existing view query (that is, the same column names in the same order and with the same data types), but it may add additional columns to the end of the list. The calculations giving rise to the output columns may be completely different."

 

Adding new columns must be at the end of the list, replacing existing columns must be done in two steps.

*.sql.view in release branch
Add new column name in the view
 
*.sql.view in master branch
Add new column name in the view
Remove old column
