import java.lang.reflect.*;
import java.util.*;

class A {

}

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    static public void doBasicReflection() {
 
         //try {
            ////either one
            ////Class c = Class.forName("java.util.Stack");
            //Class c = Stack.class;
            //Method m[] = c.getDeclaredMethods();
            //for (int i = 0; i < m.length; i++)
                //System.out.println(m[i].toString());
         //} catch (Throwable e) {
            //System.err.println(e);
         //}



         //Simulating the instanceof operator
          try {
            Class cls = Class.forName("A");
            boolean b1 = cls.isInstance(new Integer(37));
            System.out.println(b1);
            boolean b2 = cls.isInstance(new A());
            System.out.println(b2);
         }
         catch (Throwable e) {
            System.err.println(e);
         }
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        //
        doBasicReflection();
    }
}
